# -*- coding: utf-8 -*-
"""Leader&Follower Robot Controllers

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fiNY7w7pfIOaXXNn40sp57tZ3o-fAh_j
"""

# leader_controller.py

# Keyboard to give human commands, emitters and receivers to communicate, time to track seconds
from controller import Robot, Keyboard, Emitter, Receiver
import time

# --- CONFIGURATION ---
TIME_STEP = 64

EAST_Z = 0.0   # For Moving To the East Side Of The Room
WEST_Z = 0.1  # For Moving To the West Side Of The Room

class LeaderRobot:
    def __init__(self):
        self.robot = Robot()
        self.time_step = int(self.robot.getBasicTimeStep())

        self.emitter = self.robot.getDevice("emitter")
        self.receiver = self.robot.getDevice("receiver")
        self.receiver.enable(self.time_step)

        self.keyboard = Keyboard()
        self.keyboard.enable(self.time_step)

        self.command_times = {}
        self.travel_history = {"CHAI": {}, "TABLE": {}}
        self.current_target = None

        print("Press '1': Leader, find the Chai object in the (East) corner of Room 1 | '2': Stop searching for Chai. Now, locate the Table in the (West) corner | '3': Report")

    def send_to_followers(self, robot_id, action, x, z, color="NONE"):
        """ Format: TARGET_ID:ACTION:X:Z:COLOR """
        message = f"{robot_id}:{action}:{x:.2f}:{z:.2f}:{color}"
        self.emitter.send(message.encode('utf-8'))

        current_time = self.robot.getTime()
        if robot_id == "ALL":
            for fid in ["FOLLOWER1", "FOLLOWER2", "FOLLOWER3"]:
                self.command_times[fid] = current_time
        else:
            self.command_times[robot_id] = current_time

        print(f"Leader Sent -> {message}")

    def parse_and_execute(self, command_text):
        command_text = command_text.lower()
        target_x, target_z = 0.0, 0.0
        target_color = "NONE"
        valid_command = False

        if "stop" in command_text:
            self.send_to_followers("ALL", "STOP", 0, 0)
            if "locate" not in command_text and "find" not in command_text:
                return
        if "chai" in command_text:
            self.current_target = "CHAI"
            target_x, target_z = 0.8, EAST_Z
            target_color = "RED"
            valid_command = True
        elif "table" in command_text:
            self.current_target = "TABLE"
            target_x, target_z = -0.8, WEST_Z
            target_color = "BLUE"
            valid_command = True
        elif "east" in command_text:
            target_x, target_z = 0.8, EAST_Z
            target_color = "RED"
            valid_command = True
        elif "west" in command_text:
            target_x, target_z = -0.8, WEST_Z
            target_color = "BLUE"
            valid_command = True

        if valid_command:
            print(f"→ Sending target: X={target_x}, Z={target_z}, Color={target_color}")
            # Spread followers so they do not fight for the same spot
            offset = 0.1
            self.send_to_followers("FOLLOWER1", "GOTO", target_x - offset, target_z, target_color)
            self.send_to_followers("FOLLOWER2", "GOTO", target_x, target_z, target_color)
            self.send_to_followers("FOLLOWER3", "GOTO", target_x + offset, target_z, target_color)

    def display_travel_times(self):
        print("\n" + "="*30 + "\nTRAVEL TIME REPORT\n" + "="*30)
        for target in ["CHAI", "TABLE"]:
            print(f"Target: {target}")
            for fid, t in self.travel_history[target].items():
                print(f"  {fid}: {t:.2f}s")
        print("="*30)

    def run(self):
        while self.robot.step(self.time_step) != -1:
            key = self.keyboard.getKey()

            if key == ord('1'):
                self.parse_and_execute("find the Chai")
            elif key == ord('2'):
                self.parse_and_execute("find the table")
            elif key == ord('3'):
                self.display_travel_times()

            while self.receiver.getQueueLength() > 0:
                message = self.receiver.getString()
                if "ARRIVED" in message:
                    fid = message.split(":")[0]
                    if fid in self.command_times:
                        t = self.robot.getTime() - self.command_times[fid]
                        if self.current_target:
                            self.travel_history[self.current_target][fid] = t
                        print(f"Leader: {fid} confirmed target found in {t:.2f}s")
                        del self.command_times[fid]
                self.receiver.nextPacket()

if __name__ == "__main__":
    leader = LeaderRobot()
    leader.run()

# follower_controller.py

from controller import Robot, Emitter, Receiver, Camera
import math

# --- CONFIGURATION ---
TIME_STEP = 64
MAX_SPEED = 6.28
CRUISING_SPEED = 4.0
DISTANCE_TOLERANCE = 0.15 # Stop slightly earlier to allow camera scan

class FollowerRobot:
    def __init__(self):
        self.robot = Robot()
        self.name = self.robot.getName()
        self.time_step = int(self.robot.getBasicTimeStep())

        # Motors
        self.left_motor = self.robot.getDevice('left wheel motor')
        self.right_motor = self.robot.getDevice('right wheel motor')
        self.left_motor.setPosition(float('inf'))
        self.right_motor.setPosition(float('inf'))
        self.left_motor.setVelocity(0.0)
        self.right_motor.setVelocity(0.0)

        # Comms
        self.emitter = self.robot.getDevice("emitter")
        self.receiver = self.robot.getDevice("receiver")
        self.receiver.enable(self.time_step)

        # Navigation Sensors
        self.gps = self.robot.getDevice("gps")
        self.gps.enable(self.time_step)
        self.compass = self.robot.getDevice("compass")
        self.compass.enable(self.time_step)

        # Color Recognition Camera
        self.camera = self.robot.getDevice("camera(1)")
        self.camera.enable(self.time_step)
        self.camera.recognitionEnable(self.time_step)

        # Proximity Sensors
        self.ps = []
        for i in range(8):
            s = self.robot.getDevice(f'ps{i}')
            s.enable(self.time_step)
            self.ps.append(s)

        # States
        self.target_x = None
        self.target_z = None
        self.target_color = "NONE"
        self.is_moving = False
        self.mode = "NAVIGATING" # NAVIGATING, SEARCHING, FOUND

        self.avoidance_state = "NONE"
        self.avoidance_counter = 0

        print(f"{self.name} READY.")

    def set_speeds(self, left, right):
        self.left_motor.setVelocity(min(max(left, -MAX_SPEED), MAX_SPEED))
        self.right_motor.setVelocity(min(max(right, -MAX_SPEED), MAX_SPEED))

    def get_heading(self):
        north = self.compass.getValues()
        return math.atan2(north[0], north[2])

    def scan_for_color(self):
        objs = self.camera.getRecognitionObjects()
        for o in objs:
            colors = o.getColors()
            is_match = False
            if self.target_color == "RED" and colors[0] > 0.6: is_match = True
            if self.target_color == "BLUE" and colors[2] > 0.6: is_match = True

            if is_match:
                pos = o.getPositionOnImage()
                return True, pos[0] - (self.camera.getWidth() / 2)
        return False, 0

    def handle_messages(self):
        if self.receiver.getQueueLength() > 0:
            data = self.receiver.getString()
            parts = data.split(":")
            if parts[0] == self.name or parts[0] == "ALL":
                if parts[1] == "STOP":
                    self.is_moving = False
                    self.set_speeds(0,0)
                elif parts[1] == "GOTO":
                    self.target_x = float(parts[2])
                    self.target_z = float(parts[3])
                    self.target_color = parts[4]
                    self.is_moving = True
                    self.mode = "NAVIGATING"
            self.receiver.nextPacket()

    def move_to_target(self):
        if not self.is_moving:
            return

        # --- 1. SENSOR READINGS ---
        ps_values = [s.getValue() for s in self.ps]
        # Front sensors (ps0, ps1, ps6, ps7)
        front_blocked = max(ps_values[0], ps_values[1], ps_values[6], ps_values[7]) > 85.0
        # Side sensors (ps2, ps5)
        side_blocked = max(ps_values[2], ps_values[5]) > 80.0

        # --- 2. OBSTACLE AVOIDANCE STATE MACHINE ---
        if self.avoidance_state == "NONE":
            if front_blocked:
                print(f"{self.name}: Wall detected! Escaping...")
                self.avoidance_state = "ESCAPE_TURN"
                # Determine turn direction based on which side is clearer
                self.turn_direction = 1 if ps_values[7] > ps_values[0] else -1
                self.avoidance_counter = 40 # Adjust for 90-degree turn
            elif side_blocked:
                # Slight nudge away from side walls without stopping navigation
                kp_side = 0.05
                nudge = (ps_values[5] - ps_values[2]) * kp_side
                # This nudge will be added to the navigation speeds below
            else:
                nudge = 0

        if self.avoidance_state == "ESCAPE_TURN":
            # Phase 1: Spin away from the wall
            self.set_speeds(3.0 * self.turn_direction, -3.0 * self.turn_direction)
            self.avoidance_counter -= 1
            if self.avoidance_counter <= 0:
                self.avoidance_state = "ESCAPE_DRIVE"
                self.avoidance_counter = 60 # Drive forward for 60 steps to clear the corner
            return

        if self.avoidance_state == "ESCAPE_DRIVE":
            # Phase 2: Drive straight to get away from the corner
            self.set_speeds(CRUISING_SPEED, CRUISING_SPEED)
            self.avoidance_counter -= 1
            if self.avoidance_counter <= 0 or front_blocked:
                self.avoidance_state = "NONE"
            return

        # --- 3. NORMAL NAVIGATION & SEARCH ---
        # (Only reached if avoidance_state == "NONE")

        curr_x = self.gps.getValues()[0]
        curr_z = self.gps.getValues()[2]
        dist = math.sqrt((self.target_x-curr_x)**2 + (self.target_z-curr_z)**2)

        if self.mode == "NAVIGATING":
            if dist < DISTANCE_TOLERANCE:
                self.mode = "SEARCHING"
                return

            t_angle = math.atan2(self.target_x-curr_x, self.target_z-curr_z)
            error = t_angle - self.get_heading()
            while error > math.pi: error -= 2*math.pi
            while error < -math.pi: error += 2*math.pi

            # Combine Navigation with the side-wall nudge
            self.set_speeds(CRUISING_SPEED + error*4 + nudge, CRUISING_SPEED - error*4 - nudge)

        elif self.mode == "SEARCHING":
            found, img_err = self.scan_for_color()
            if found:
                if abs(img_err) < 2:
                    self.set_speeds(0,0)
                    self.is_moving = False
                    self.emitter.send(f"{self.name}:ARRIVED:TargetFound".encode('utf-8'))
                else:
                    self.set_speeds(img_err*0.1, -img_err*0.1)
            else:
                self.set_speeds(2.0, -2.0) # Search spin

    def run(self):
        while self.robot.step(self.time_step) != -1:
            self.handle_messages()
            self.move_to_target()

if __name__ == "__main__":
    follower = FollowerRobot()
    follower.run()